exit early on error
If packages fail to install for example, exit immediately.
The script can be called again to complete the process.

diff --git a/utils/openstack-demo-install b/utils/openstack-demo-install
--- a/utils/openstack-demo-install
+++ b/utils/openstack-demo-install
@@ -18,6 +18,8 @@
 # under the License.
 #
 
+set -e # exit on error. This script is restartable
+
 if [ $(id -u) -ne 0 ]; then
   echo 'Please run this as the root user' >&2
   exit 1
